version: "3.9"
services:
  spring_boot_api:
    build: spring_boot_api
    container_name: spring_boot_api
    stdin_open: true
    ports:  
      - 8080:8080
    tty: true
  user-interface:
    build: user_interface
    container_name: user-interface
    stdin_open: true
    ports:
      - 3000:3000
    tty: true